version: 0.2

env:
  parameter-store:
    private_key_github: "github_key"
    github_mail: "github_mail"
    account: "account"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR!
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI_LOGIN=$account.dkr.ecr.us-west-2.amazonaws.com/challenge_login
      - REPOSITORY_URI_AUTHORIZER=$account.dkr.ecr.us-west-2.amazonaws.com/challenge_authorizer
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - GIT_BRANCH=$(echo $CODEBUILD_SOURCE_VERSION)
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image $REPOSITORY_URI_LOGIN - $COMMIT_HASH ...
      - cd login
      - docker build -t $REPOSITORY_URI_LOGIN:$COMMIT_HASH .
      - docker tag $REPOSITORY_URI_LOGIN:$COMMIT_HASH $REPOSITORY_URI_LOGIN:$IMAGE_TAG
      - cd ..
      - echo Building the Docker image $REPOSITORY_URI_LOGIN - $COMMIT_HASH ...
      - cd authorizer
      - docker build -t $REPOSITORY_URI_AUTHORIZER:$COMMIT_HASH .
      - docker tag $REPOSITORY_URI_AUTHORIZER:$COMMIT_HASH $REPOSITORY_URI_AUTHORIZER:$IMAGE_TAG
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images $REPOSITORY_URI_LOGIN - $IMAGE_TAG ...
      - docker push $REPOSITORY_URI_LOGIN:$IMAGE_TAG
      - echo Pushing the Docker images $REPOSITORY_URI_AUTHORIZER - $IMAGE_TAG ...
      - docker push $REPOSITORY_URI_AUTHORIZER:$IMAGE_TAG
      - mkdir -p ~/.ssh
      - echo "$private_key_github" > ~/.ssh/id_rsa
      - chmod 0600 ~/.ssh/id_rsa
      - echo Cloning Serverless Repository  ...
      - git clone git@github.com:Fercho120/Kueski_Challenge.git
      - cd Kueski_Challenge
      - git checkout main
      - echo Configuring Serverless Repository  ...
      - git config --global user.email "$github_mail"
      - git config --global user.name "Fercho120"
      - echo Replacing Authorizer Docker Image into serverless.yml  ...
      - sed -i "78s#.*#\ \ \ \ image\:\ $REPOSITORY_URI_LOGIN:$IMAGE_TAG#" serverless.yml
      - sed -i "90s#.*#\ \ \ \ image\:\ $REPOSITORY_URI_AUTHORIZER:$IMAGE_TAG#" serverless.yml
      - git add serverless.yml
      - git commit -m "main - change image-docker-login and image-docker-authorizer buildspec"
      - echo Pushing changes Serverless Repository ...
      - git push origin main